infrastructure/templates/warehouse.yaml
When this policy is attached to the user, they will be able to list, and read from the upload bucket, through it's direct link:
* If console user, then directly through `https://s3.console.aws.amazon.com/s3/buckets/BUCKETNAME/`
* If programmatic access, then through `s3://BUCKETNAME/`
where `BUCKETNAME` is the one created by the template.
Connects-to: #11 
Tested on our faculty development account.
=> Add group that can view the whole upload bucket, in read-only mode

infrastructure/create.py, infrastructure/templates/warehouse.yaml
Usage through command line flags at the moment. If no flags are applied,
then all IPs are allowed. Multiple ranges can be provided by adding
the flag multiple times, such as:
```
python create.py -s suffix -a 1.2.3.4/24 -a 5.6.7.8/24
```
By default the upload is not limited (i.e. the value `0.0.0.0/0` is set). In subsequent updates, if no `-a`/`--allowed-cidr` flags are passed, the previous values are used (to make it more difficult to accidentally open up access by not passing the flags).
Connects-to: #9
=> Allow specifying CIDR blocks from where uploads to "raw/" are allowed

.github/CODEOWNERS
Anyone else should be on this list? @edent for example? (just asking whether preferred, or required at all, though feels definitely optional)
The point of [`CODEOWNERS`](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) is to automatically add specific people as reviewers on PRs, and thus there's smaller number here, so it's more signal and not noise for people.
=> Add CODEOWNERS, closes #18

infrastructure/templates/warehouse.yaml
* CT & patient data
* MRI & patient data
* X-ray & patient data
* All access
The final all access is useful to be able to allow "sync"-ing
the entire training folder, for the other permissions they can
only list the relevant modality, metadata, and data folders,
and thus syncing of `training/` is not workable.
Connects-to: #14
=> loader: add IAM policies and groups for training access

infrastructure/create.py
Otherwise it seems the "UsePreviousValue" setting doesn't take "default"
into account as "previous" value.
=> infrastructure: at bucket creation type set allowed CIDR to default value

docs/source/_templates/footer.html
To connect easier the site and the source, when people navigate to the page.
=> docs: add extra-footer to link back to the source code, closes #42

docs/source/index.rst
Instead of hard-linking the positive/negative clinical data template documents, link to their hosting page.
Preview:
=> docs: update template links to Data and Status formats, closes #55

infrastructure/templates/warehouse.yaml
If the delimiter is included, `aws sync` cannot work on the training folders, as it doesn't send a delimiter.
Related to https://github.com/aws/aws-cli/issues/5202
=> infra: relax check on prefix to list training data

infrastructure/templates/warehouse.yaml, warehouse-loader/README.md, warehouse-loader/warehouseloader.py
This is more in line with the `ct` and `mri` folder/prefix names, and clashing less with the `...-metadata` prefix pattern.
=> structure: rename `x-ray` folder to `xray`

infrastructure/templates/warehouse.yaml
Turns out that inventory files won't really work with S3 Select, as the sizes are grown above the max queryable size. If we need to download the files to work together with anyways, then simpler (and smaller) CSV (Gzip'd by default) should be easier to deal with.
=> infrastructure: change inventory format to CSV and limit fields

infrastructure/templates/warehouse.yaml
Only their own users, naturally.
Based on the cut-down version of [this example AWS doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam_credentials_console.html).
=> infra: allow key rotation for users in any of the groups

infrastructure/container/Dockerfile
Installation of the Python code was missing these after recommended packages were removed by the suggestion of the linter.
=> container: add missing explicit dependencies

infrastructure/templates/warehouse.yaml
When a new "prod" image is tagged, previous versions will be untagged, clean those up over time, or over pushes.
=> infra: Docker repository to only keep 5 untagged images

infrastructure/templates/warehouse.yaml
Start off with 2 years, that should be on the safe side, even though
we'd be okay with a few months for this particular part.
Closes: #139 
=> infra: set log retention of pipeline logs

infrastructure/templates/warehouse.yaml
Accessing the `validation/` prefix and contents only.
Connects-to: #11
=> infrastructure: add "validation" user group to access validation files

infrastructure/templates/warehouse.yaml
Current use of Pandas is a bit too much for the given instance sizes, before refactoring, can do a bit of scaling.
=> scaling up pipeline task due to the memory use required

infrastructure/container/Dockerfile, infrastructure/container/fetch_and_run.sh
Otherwise `setup.py` cannot pin dependencies exactly...
=> container: allow installing from requirements file to pin dependencies

.github/workflows/codeql-analysis.yml
From the logs it showed:
> Warning: 1 issue was detected with this workflow:
> git checkout HEAD^2 is no longer necessary. Please remove
> this step as Code Scanning recommends analyzing the merge
> commit for best results.
=> workflows: remove no longer necessary step from codeql flow

dashboard/dashboard/requirements.in, dashboard/dashboard/requirements.txt, dashboard/dashboard/run.py
Timeloop works with Flask but not with the gunicorn, so that the deployed dashboard didn't actually update before.
=> dashboard: new periodic task exec library that works with gunicorn

warehouse-loader/bin/submittingcentres
The submittingcentres task saves results to /tmp/message.txt,
add to that the pipeline message, and send the file contents.
=> loader: submittingcentres results to be included in email notification

dashboard/dashboard/templates/macros/navbar.html, infrastructure-dashboard/dashboard/dashboard/dashboard_stack.py
* removing the `development` marking from the dashboard header
* making provisioned cpu/memory explicit in the infrastructure, to have it ready to change when/if needed.
=> Dashboard tuning

infrastructure/templates/warehouse.yaml, warehouse-loader/warehouse/warehouseloader.py
Previous 2GB limit was too optimistic, the actual usage is somewhat higher than that, so bump things to the max allowed for 1vCPU Fargate tasks, to have buffer. Memory usage is pretty cheap and thus this will make things safer.
=> loader: pipeline improvements for memory management
