- .github/workflows/infrastructure.yml
Also fix up `working-directory` settings in the existing actions
> Add infrastructure check GitHub Action, starting with cloudformation linting

- infrastructure/create.py
- infrastructure/templates/warehouse.yaml
This logs all events related to the data warehouse bucket with CloudTrail. 
The events are logged to a separate bucket called `nccid-data-warehouse-object-logs`.
A typical event looks like the following (this corresponds to user `chest-data-warehouse-uploader` uploading to `raw/2020-04-05/data/02.json`:
```json
{
"eventVersion": "1.07",
"userIdentity": {
"type": "IAMUser",
"principalId": "AIDA5GFUR77HYXJ7C5P7H",
"arn": "arn:aws:iam::906616766415:user/chest-data-warehouse-uploader",
"accountId": "906616766415",
"accessKeyId": "AKIA5GFUR77HZLAJHGYI",
"userName": "chest-data-warehouse-uploader"
},
"eventTime": "2020-04-06T17:49:55Z",
"eventSource": "s3.amazonaws.com",
"eventName": "PutObject",
"awsRegion": "eu-west-2",
"sourceIPAddress": "35.178.135.24",
"userAgent": "[Boto3/1.11.16 …
```
> Log all warehouse bucket events with CloudTrail

- docs/source/index.rst
> Add link to the data collection website by Royal Surrey

- CODE_OF_CONDUCT.md
This adds the NHSX standard Code of Conduct. Please can you add a suitable email address to the Enforcement section.
> Code of Conduct - please review and update

- infrastructure/templates/warehouse.yaml
> infrastructure: add IAM policy / group for ETL uploaders

- infrastructure/templates/warehouse.yaml
Bucket lifecycle rule for general cleanup
Connects-to: #17
> infrastructure: remove incomplete uploads

- .github/ISSUE_TEMPLATES/BUG_REPORT.md
- .github/ISSUE_TEMPLATES/FEATUE_REQUEST.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
* contributing
* PR template
* issue templates
> Add templates and community docs

- warehouse-loader/warehouseloader.py
Various pipeline improvements.
> Pipeline improvements

- infrastructure/create.py
- infrastructure/templates/warehouse.yaml
It wasn't used nor effective, and likely just complicates things at the
moment.
> infra: remove bucket policy of whitelisting IPs for upload, closes #49

- warehouse-loader/README.md
Add more info to the loader readme.
> loader: update README

- docs/source/index.rst
New contributing hospital to add to the docs page
> docs: add new hospital to the docs

- .github/workflows/site-deployment.yml
- .github/workflows/site-preview.yml
- docs/source/conf.py
Deploying docs on S3 for preview. Closes #66
> Docs preview deployment

- .github/workflows/loader.yml
- warehouse-loader/warehouseloader.py
A bit of internal reorganisation to reduce computing complexity of some of the functions.
> loader: reduce complexity of user data processing, closes #61

- warehouse-loader/submittingcentres.py
Otherwise, if the order keeps changing, it's more difficult to which centres to include in the `config.json`. Closes #77
> loader: sort submittingcentres output for better readability

- warehouse-loader/warehouseloader.py
Implementing a structure that was used very well in other places: 
CovidXXX (Folder) ->  StudyIUID (folder) -> SeriesIUID (Folder) -> DICOM files (files)
> loader: implement updated folder structure for images and metadata

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/PULL_REQUEST_TEMPLATE.md
Some of the templates needed extra fields, or needed headers removed as otherwise are clunkier to use.
> templates: update based on experience

- docs/source/index.rst
> Update hospital link

- .github/workflows/site-preview.yml
- infrastructure/README.md
- infrastructure/create.py
- infrastructure/docs-preview.py
- infrastructure/templates/docs-preview.yaml
Cloudformation template for the hosting, and information on the use.
Closes #68
> Preview bucket infrastructure

- docs/requirements.txt
- docs/source/_static/css/nhsx.css
- docs/source/access_examples.rst
- docs/source/index.rst
Adding "Accessing data" section to the docs.
Closes #36
> docs: adding data access examples

- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- docs/source/scripts/hospital_locations.csv
- docs/source/scripts/maps.py
Plot the participating hospitals on a map of the UK
Closes #83
> docs: add hospital map

- docs/source/data_access.rst
> docs: tuning text based on feedback

- infrastructure/templates/warehouse.yaml
> infra: add inventory bucket and other refinements

- .github/workflows/site-preview.yml
The previous URL migth cause surprise.
> Use S3 Website URL for deployment and unify variables in workflow

- docs/source/index.rst
- docs/source/scripts/hospital_locations.csv
> Ottavia ber patch 1

- .github/workflows/site-preview.yml
- README.md
> Deployment improvements

- warehouse-loader/requirements-dev.txt
- warehouse-loader/test_basics.py
- warehouse-loader/warehouseloader.py
> loader: implement partial download of DICOM files

- warehouse-loader/test_basics.py
- warehouse-loader/warehouseloader.py
> loader: update KeyCache logic and add test

- infrastructure/container/Dockerfile
- infrastructure/container/fetch_and_run.sh
- infrastructure/templates/warehouse.yaml
Setting up task running within AWS directly. Connects to #134 
First iteration, run things manually by setting up the right tasks from task definitions.
> infrastructure: running tasks all in AWS

- .github/workflows/container.yml
- README.md
- infrastructure/container/Dockerfile
Static testing with [hadolint](https://github.com/hadolint/hadolint). Closes #142
> tests: add linting for the shipped Dockerfile

- infrastructure/templates/warehouse.yaml
- warehouse-loader/bin/submittingcentres
- warehouse-loader/bin/warehouseloader
> allow pipeline tasks to send notifications (through SNS)

- .github/workflows/codeql-analysis.yml
Code scanning for enhanced information on code quality.
Adding it to try if it provides any useful info (since it's a _beta_ feature).
> CodeQL analysis workflow

- warehouse-loader/warehouse/components/services.py
- warehouse-loader/warehouse/submittingcentres.py
> Docstring updates

- docs/source/NCCID_Collaborative.rst
> add person to collaborative

- infrastructure/container/Dockerfile
> docker: update pip package version as changed from package repos

- infrastructure/templates/warehouse.yaml
- warehouse-loader/requirements.txt
- warehouse-loader/setup.py
- warehouse-loader/tests/test_basics.py
- warehouse-loader/warehouse/components/services.py
- warehouse-loader/warehouse/submittingcentres.py
- warehouse-loader/warehouse/warehouseloader.py
> loader: use inventory if available

- infrastructure/templates/warehouse.yaml
> infrastructure: add auditor role with r/o access to object logs

- infrastructure/templates/warehouse.yaml
Should help with warehouse analytics
> infra: save last modified date in the inventory as well

- warehouse-loader/warehouse/components/services.py
THe headers are properly listed as things have changed in #168.
> loader: correctly parse updated inventory

- docs/source/faq.rst
> docs: update docs with tooling

- warehouse-loader/tests/test_basics.py
- warehouse-loader/tox.ini
The original region choice doesn't seem to work, need to set `us-east-1`
along the lines of https://stackoverflow.com/a/64539434/171237
> update moto and change some tests

- docs/source/index.rst
- docs/source/scripts/hospital_locations.csv
> add Oxford University Hospitals to the website

- .github/CODEOWNERS
> simplify codeowners list after staffing changes

- infrastructure/templates/warehouse.yaml
Also add to CloudTrail logs as well, to log backup bucket access.
Closes #10
> create backup bucket and replication rules for the warehouse

- docs/source/index.rst
- docs/source/other_datasets.rst
> add other datasets page to the docs

- infrastructure-dashboard/nccid-redirect/.gitignore
- infrastructure-dashboard/nccid-redirect/README.md
- infrastructure-dashboard/nccid-redirect/app.py
- infrastructure-dashboard/nccid-redirect/cdk.json
- infrastructure-dashboard/nccid-redirect/lambda/lambda-handler.py
- infrastructure-dashboard/nccid-redirect/nccid_redirect/nccid_redirect_stack.py
- infrastructure-dashboard/nccid-redirect/requirements.txt
- infrastructure-dashboard/nccid-redirect/setup.py
- infrastructure-dashboard/nccid-redirect/source.bat
> dns-infrastructure for the domain redirection

- docs/source/NCCID_Collaborative.rst
> docs: add new trusts to the collaborative

- docs/source/resources.rst
> docs: update formatting in FAQ that was missed earlier

- .github/workflows/stats-page.yml
- docs/source/scripts/stats.py
> workflow: generate stats page automatically

- .github/workflows/stats-page.yml
> stats: allow manual trigger for workflow

- .github/workflows/stats-page.yml
> Stats secrets

- docs/source/project_summaries.rst
3 new ones, and some formatting fixes elsewhere on the page.
> docs: add more project summaries

- .github/workflows/dashboard-deploy.yml
> actions: fix where the image is built from

- .github/workflows/dashboard-deploy.yml
> debug and hopefully fix dashboard deploy action

- infrastructure-dashboard/dashboard/README.md
> dashboard: installing the dashboard infra CDK stuff need the README file

- infrastructure/templates/warehouse.yaml
> infrastructure for data processing

- infrastructure-dashboard/dashboard/dashboard/dashboard_stack.py
> fix stack variable reference

- dashboard/Dockerfile
> enable debug log on dashboard

- dashboard/Dockerfile
- dashboard/dashboard/guniconf.py
> add configuration file to be able to adjust the parameters

- infrastructure-dashboard/dashboard/dashboard/dashboard_stack.py
Required by the authentication of the dashboard
> stack: update cloudfront behavour to allow query strings forwarding and more methods

- dashboard/dashboard/pages/__init__.py
> dashboard: fix title of pages

- dashboard/dashboard/guniconf.py
- infrastructure-dashboard/dashboard/dashboard/dashboard_stack.py
Small changes to how containers are run.
* container log level reduction
* enabling container insights
* stack clean
> Containers

- dashboard/dashboard/README.md
- dashboard/dashboard/dataset/__init__.py
- dashboard/dashboard/env.template
- dashboard/dashboard/pages/__init__.py
- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/images/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/quality/__init__.py
> Add new pages and documentation

- dashboard/dashboard/pages/hospitals/__init__.py
* Loading animation for interactive plots
* updated hospital plot
Closes #226
> Dashboard improvements

- infrastructure/templates/warehouse.yaml
And task definition family names.
> Resource bump

- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
Add some people page content.
Also some fixes for other pages.
> People page

- dashboard/dashboard/server.py
- dashboard/dashboard/templates/404.html
> dashboard: add error page for 404

- dashboard/dashboard/pages/images/__init__.py
> dashboard: initial view of image

- dashboard/dashboard/pages/patients/__init__.py
> dashboard: patients page gener breadown more informative

- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/images/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/summary/__init__.py
Plot and display improvements across the board.
> Page tuning

- dashboard/dashboard/pages/patients/__init__.py
> Pages tuning

- dashboard/dashboard/pages/quality/columns.py
> dashboard: add missing module

- dashboard/dashboard/README.md
- dashboard/dashboard/pages/quality/__init__.py
Import on Python 3.6 and README.
> Dashboard fixes

- dashboard/dashboard/pages/quality/__init__.py
> Dashboard update

- docs/source/scripts/stats.py
- docs/source/scripts/stats_storage.csv
- infrastructure/templates/warehouse.yaml
> docs: change public dashboard to use the preprocessed data and decimal scale

- docs/source/index.rst
- docs/source/scripts/hospital_locations.csv
> website: add Sheffield Teaching Hospitals to the website

- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/quality/__init__.py
- dashboard/dashboard/pages/quality/columns.py
- dashboard/dashboard/pages/summary/__init__.py
> Cosmetic fixes

- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/images/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
> Patient timeseries

- dashboard/dashboard/dataset/__init__.py
- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/images/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/quality/__init__.py
- dashboard/dashboard/pages/summary/__init__.py
- dashboard/dashboard/pages/tools.py
Plus a a bit of small logic cleanup .
> Adjustments to potential race condition when using the warehouse's data

- dashboard/dashboard/pages/hospitals/__init__.py
> Last submission

- dashboard/dashboard/pages/quality/__init__.py
> dashboard: percentage display for table and chart

- dashboard/dashboard/pages/quality/__init__.py
> dashboard: remove unnecessary rounding left over from previous change

- dashboard/dashboard/dataset/__init__.py
- dashboard/dashboard/pages/__init__.py
- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/images/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/quality/__init__.py
- dashboard/dashboard/pages/summary/__init__.py
- dashboard/dashboard/pages/tools.py
- dashboard/dashboard/pyproject.toml
- dashboard/dashboard/run.py
- dashboard/dashboard/setup.cfg
- dashboard/dashboard/tox.ini
Setting up `tox` to do code check and formatting. Run `tox -e prepare` to do the formatting task (import sorting, black, flake8 checks)
Also removed some stale code and changed a few bits slightly, ~~functionality should remain completely the same as before~~.
Added an extra commit for the note headers as discussed.
> dashboard: formatting data and add tooling, removing commented out code

- warehouse-loader/tests/test_cloud.py
- warehouse-loader/warehouse/warehouseloader.py
> loader: adjustment to yielding at different steps of the pipeline

- warehouse-loader/tests/test_dryrun.py
> loader: add tests for running dry run with the "DRY_RUN" env var

- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/quality/__init__.py
* showing enriched data on the patients page, and warn about it
* properly use the non-enriched data on the data quality page
Depends on #277
> Dashboard enrichment

- infrastructure/templates/warehouse.yaml
* container resizing for less memory allocation (as now that should be enough)
* task definition name update
> Infrastructure changes

- docs/source/NCCID_Collaborative.rst
- docs/source/index.rst
- docs/source/other_datasets.rst
- docs/source/project_summaries.rst
- docs/source/scripts/hospital_locations.csv
> Website updates

- .github/CODEOWNERS
> add extra code-owner

- infrastructure-dashboard/dashboard/README.md
- infrastructure-dashboard/nccid-redirect/README.md
- infrastructure/README.md
> Fixes to readmes

- dashboard/dashboard/pages/__init__.py
- dashboard/dashboard/pages/hospitals/__init__.py
- dashboard/dashboard/pages/patients/__init__.py
- dashboard/dashboard/pages/quality/__init__.py
- infrastructure/create.py
- infrastructure/templates/warehouse.yaml
* dashboard improvements and hardening
* typo fixes across the board
> Various fixups based on feedback

- dashboard/dashboard/pages/__init__.py
> dashboard: add back metas and css tags otherwise sidebar misbehaves.

- .github/CODEOWNERS
> add new code owners

- warehouse-loader/tests/test_basics.py
- warehouse-loader/tests/test_cloud.py
- warehouse-loader/warehouse/dataprocess.py
> Adjustments and extra tests

- .github/CODEOWNERS
> codeowners: remove @imrehg from list

- docs/source/AI_Performance_Assessment.rst
> Adjust comment on reviewers

- docs/source/project_summaries.rst
> Edit data users

- .github/workflows/site-deployment.yml
> Remove base path on production docs build

- .github/workflows/site-deployment.yml
> Reinstate base path and include `docs/` on gh-pages build step

- docs/components/layouts/PageLayout.js
> Remove trailing slash on search action

- .github/workflows/stats-page.yml
- docs/components/layouts/parts/Header.js
Also removed the trailing slash on the search form
> Stats script location

- docs/documentation/home.mdx
> Fix document links on overview page

- docs/documentation/project-summaries.mdx
> Update project description
